/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.ner.facade.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Class { 
  ORGANIZATION, LOCATION, PERSON, MISC, MONEY, PERCENT, DATE, TIME, DISEASE, PROTEIN, DRUG, COMPOUND, GENE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Class\",\"namespace\":\"org.librairy.service.ner.facade.model\",\"symbols\":[\"ORGANIZATION\",\"LOCATION\",\"PERSON\",\"MISC\",\"MONEY\",\"PERCENT\",\"DATE\",\"TIME\",\"DISEASE\",\"PROTEIN\",\"DRUG\",\"COMPOUND\",\"GENE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
