/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.librairy.service.ner.facade.model;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface NerService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"NerService\",\"namespace\":\"org.librairy.service.ner.facade.model\",\"types\":[{\"type\":\"enum\",\"name\":\"Class\",\"symbols\":[\"ORGANIZATION\",\"LOCATION\",\"PERSON\",\"MISC\",\"MONEY\",\"PERCENT\",\"DATE\",\"TIME\",\"DISEASE\",\"PROTEIN\",\"DRUG\",\"COMPOUND\",\"GENE\"]},{\"type\":\"record\",\"name\":\"Entity\",\"fields\":[{\"name\":\"text\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"class\",\"type\":\"Class\"},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]},{\"type\":\"record\",\"name\":\"Annotation\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"text\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"class\",\"type\":\"Class\"},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"start\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"end\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"references\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}]}],\"messages\":{\"identify\":{\"request\":[{\"name\":\"text\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"filter\",\"type\":{\"type\":\"array\",\"items\":\"Class\"}}],\"response\":{\"type\":\"array\",\"items\":\"Entity\"}},\"annotate\":{\"request\":[{\"name\":\"text\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"filter\",\"type\":{\"type\":\"array\",\"items\":\"Class\"}}],\"response\":{\"type\":\"array\",\"items\":\"Annotation\"}}}}");
  java.util.List<org.librairy.service.ner.facade.model.Entity> identify(java.lang.String text, java.util.List<org.librairy.service.ner.facade.model.Class> filter) throws org.apache.avro.AvroRemoteException;
  java.util.List<org.librairy.service.ner.facade.model.Annotation> annotate(java.lang.String text, java.util.List<org.librairy.service.ner.facade.model.Class> filter) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends NerService {
    public static final org.apache.avro.Protocol PROTOCOL = org.librairy.service.ner.facade.model.NerService.PROTOCOL;
    void identify(java.lang.String text, java.util.List<org.librairy.service.ner.facade.model.Class> filter, org.apache.avro.ipc.Callback<java.util.List<org.librairy.service.ner.facade.model.Entity>> callback) throws java.io.IOException;
    void annotate(java.lang.String text, java.util.List<org.librairy.service.ner.facade.model.Class> filter, org.apache.avro.ipc.Callback<java.util.List<org.librairy.service.ner.facade.model.Annotation>> callback) throws java.io.IOException;
  }
}